#!/bin/bash
#
# Copyright 2023-2026 Gaël PORTAY
#           2023-2026 Rtone
#
# SPDX-License-Identifier: LGPL-2.1-only
#

# An implementation of a RAUC custom bootloader backend for the Raspberry Pi
# firmware.
#
# https://rauc.readthedocs.io/en/latest/integration.html#custom
#
# It uses the optional configuration file autoboot.txt in conjonction with the
# feature tryboot to follow the update flow for A/B booting example defined in
# the online documentation.
#
# https://www.raspberrypi.com/documentation/computers/config_txt.html#autoboot-txt
# https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#fail-safe-os-updates-tryboot
# https://www.raspberrypi.com/documentation/computers/config_txt.html#example-update-flow-for-ab-booting

set -e

warning() {
	echo "Warning: $*" >&2
}

error() {
	echo "Error: $*" >&2
}

debug() {
	if [[ "${DEBUG:-0}" -eq 0 ]]
	then
		return
	fi

	echo "Debug: $*" >&2
}

# Trivial .ini-like syntax parser.
#
#	[section]
#	key=value
#	...
#
# Parse the given file and set every section's key-value pairs to variables.
# It sets bash arrays to list sections and every section's keys.
#
# See:
#  - The bash array INI holds the sections defined in the file.
#  - The bash array INI__<section> holds the <key>s defined in the <section>.
#  - The variable INI__<section>__<key> holds the <key>'s <value>.
#
# Example:
#
#	$ cat /boot/autoboot.txt
# 	[all]
# 	tryboot_a_b=1
# 	boot_partition=2
# 	[tryboot]
# 	boot_partition=3
#
#	$ source_file /boot/autoboot.txt
#
#	$ echo "${INI[@]}"
#	all tryboot
#
#	$ echo "${INI__ALL[@]}"
#	tryboot_a_b boot_partition
#
#	$ echo "${INI__TRYBOOT[@]}"
#	boot_partition
#
#	$ echo "$INI__ALL__TRYBOOT_A_B"
#	1
#
#	$ echo "$INI__ALL__BOOT_PARTITION"
#	2
#
#	$ echo "$INI__TRYBOOT__BOOT_PARTITION"
#	3
source_file() {
	local lines
	local line
	local __s

	unset INI "${!INI@}"
	mapfile -t lines <"$1"
	for line in "${lines[@]}"
	do
		if [[ "$line" =~ ^\[(.*)\]$ ]]
		then
			__s="${BASH_REMATCH[1]}"
			__s="${__s//./_}"
			__s="${__s//-/_}"
			eval "INI+=('${BASH_REMATCH[1]}')"
		elif [[ "$line" =~ ^([A-Za-z0-9_-]+)=(.*)$ ]]
		then
			local __p
			local __v

			__p="${BASH_REMATCH[1]}"
			__p="${__p//./_}"
			__p="${__p//-/_}"
			__v="${BASH_REMATCH[2]}"
			eval "INI__${__s^^}__${__p^^}='$__v'"
			eval "INI__${__s^^}+=('${BASH_REMATCH[1]}')"
		fi
	done
}

# Output the bootname's slot of the given boot_partition number using the RAUC
# system.conf file.
#
# Examples:
#
#	$ cat /usr/lib/rauc/system.conf
#	(...)
# 	[slot.firmware.0]
# 	device=/dev/mmcblk0p2
# 	bootname=2
#	(...)
#
# 	[slot.firmware.1]
# 	device=/dev/mmcblk0p3
# 	bootname=3
#	(...)
#
# 	[slot.rootfs.0]
# 	device=/dev/mmcblk0p5
# 	parent=firmware.0
#	(...)
#
# 	[slot.rootfs.1]
# 	device=/dev/mmcblk0p6
# 	parent=firmware.1
#	(...)
#
#	$ get_slot 1
#	/usr/lib/rauc/system.conf: 1: No such bootname
#
#	$ get_slot 2
#	2
#
#	$ get_slot 3
#	3
get_slot() {
	local i

	source_file "${RAUC_SYSTEM_CONF:-/usr/lib/rauc/system.conf}"
	for i in "${INI[@]}"
	do
		local partition
		local bootname
		local v

		if ! [[ "$i" =~ ^slot\. ]]
		then
			continue
		fi

		v="$i"
		v="${v//./_}"
		v="${v//-/_}"
		eval "bootname=\$INI__${v^^}__BOOTNAME"
		if [[ "$bootname" != "$1" ]]
		then
			continue
		fi

		echo "$bootname"
		unset INI "${!INI@}"
		return
	done

	warning "${RAUC_SYSTEM_CONF:-/usr/lib/rauc/system.conf}: $1: No such bootname"
	unset INI "${!INI@}"
	return 1
}

# Get the oneshot reboot flag if the firmware is set to run tryboot at next
# reboot.
#
# Examples:
#
# If the oneshot reboot flag is unset:
#
#	$ vcmailbox 0x00030064 4 0 0
#	0x0000001c 0x80000000 0x00030064 0x00000004 0x80000004 0x00000000 0x00000000
#	                                                                ^ unset
#
# If the oneshot reboot flag is set:
#
#	$ vcmailbox 0x00030064 4 0 0
#	0x0000001c 0x80000000 0x00030064 0x00000004 0x80000004 0x00000001 0x00000000
#	                                                                ^ set
get_reboot_flag() {
	local values

	if ! read -r -a values < <(vcmailbox 0x00030064 4 0 0)
	then
		error "reboot: Cannot get oneshot reboot flag"
		return 1
	fi

	echo "$((values[5]))"
}

# Set or clear the oneshot reboot flag to cause the firmware to run tryboot or
# not at next reboot.
#
# The firmware uses the boot_partition defined in the [tryboot] section and it
# loads the alternate configuration file tryboot.txt instead of config.txt at
# next boot.
#
# https://www.raspberrypi.com/documentation/computers/config_txt.html#the-tryboot-filter
#
# Note: It is equivalent to run `sudo reboot "0 tryboot"` at the exception the
# system does not reboot.
#
# https://github.com/raspberrypi/linux/commit/777a6a08bcf8f5f0a0086358dc66d8918a0e1c57
#
# Example:
#
#	$ set_reboot_flag 1
# 	0x0000001c 0x80000000 0x00038064 0x00000004 0x80000004 0x00000000 0x00000000
#
# 	$ vcmailbox 0x00030064 4 0 0
# 	0x0000001c 0x80000000 0x00030064 0x00000004 0x80000004 0x00000001 0x00000000
set_reboot_flag() {
	vcmailbox 0x00038064 4 0 "$1"
}

# Swap the boot_partition configurations in autoboot.txt to cause the firmware
# to use the boot_partition that is defined in the [tryboot] section as the
# default boot_partition.
#
# https://www.raspberrypi.com/documentation/computers/config_txt.html#example-update-flow-for-ab-booting
#
# Example:
#
#	$ cat /boot/autoboot.txt
# 	[all]
# 	tryboot_a_b=1
# 	boot_partition=2
# 	[tryboot]
# 	boot_partition=3
#
#	$ set_primary_persistent
#
#	$ cat /boot/autoboot.txt
# 	[all]
# 	tryboot_a_b=1
# 	boot_partition=3
# 	[tryboot]
# 	boot_partition=2
set_primary_persistent() {
	local tryboot_boot_partition
	local all_boot_partition

	source_file "${RASPBERRYPI_AUTOBOOT_TXT:-/boot/autoboot.txt}"
	all_boot_partition="$INI__ALL__BOOT_PARTITION"
	tryboot_boot_partition="$INI__TRYBOOT__BOOT_PARTITION"

	sed -e "/^boot_partition=$all_boot_partition/s,=.*,_tmp=$tryboot_boot_partition," \
	    -e "/^boot_partition=$tryboot_boot_partition/s,=.*,_tmp=$all_boot_partition," \
	    -e "s,boot_partition_tmp=,boot_partition=," \
	    "${RASPBERRYPI_AUTOBOOT_TXT:-/boot/autoboot.txt}" >"${RASPBERRYPI_AUTOBOOT_TXT:-/boot/autoboot.txt}".tmp

	mv "${RASPBERRYPI_AUTOBOOT_TXT:-/boot/autoboot.txt}"{.tmp,}
}

# RAUC custom bootloader backend interface
#
# https://rauc.readthedocs.io/en/latest/integration.html#custom-bootloader-backend-interface

# Output "good" if the given slot is the booted slot.
#
# Output "bad" otherwise (i.e. if the given slot is **NOT** the booted slot).
#
# Note: The other slot (i.e. the non-boot'ed slot) is marked as "bad" since its
# status is unknown and no persistent marker is used. However, it is considered
# "good" if the oneshot reboot flag is set.
#
# Note 2: The file tryboot.txt is **NOT** used as the persistent status marker
# for the slot. Its presence (or its absence) would indicate the slot is "bad"
# (or "good") in the future; deeper testing is needed to rule this behaviour.
#
# Note 3: The boot partitions are untouched for safety reasons even though they
# would not if the kernel is updated; the kernel is part of the boot partition,
# and its modules are part of the root filesystem. As a consequence, a kernel
# update implies to update the kernel image in the boot partition to keep it
# synced with its modules in the root partition.
get_state() {
	local current

	if ! current="$(get_current)"
	then
		error "partition: Cannot get current partition"
		return 1
	fi

	# the slot is the booted slot, status is good
	if [[ "$1" == "$current" ]]
	then
		debug "Detected booted slot"
		echo good
		return
	fi

	# the slot is not the booted slot, status is bad
	echo bad
}

# Set the other slot as primary persistently in autoboot.txt if the given slot
# is not the primary slot, if the given state is "good", if the oneshot reboot
# flag is unset **AND** if booted using tryboot.
#
# Do nothing otherwise.
set_state() {
	local primary
	local tryboot
	local reboot

	if ! primary="$(get_primary)"
	then
		error "primary: Cannot get slot"
		return 1
	fi

	if ! slot="$(get_slot "$1")"
	then
		error "$1: Cannot get slot"
		return 1
	fi

	# the slot is bad, do nothing
	if [[ "$2" == bad ]]
	then
		debug "Ignore bad bootstate"
		return
	fi

	if ! tryboot="$(fdtget /sys/firmware/fdt /chosen/bootloader tryboot)"
	then
		error "tryboot: Cannot get bootloader tryboot"
		return 1
	fi

	# the tryboot is unset, do nothing
	if [[ "$tryboot" -eq 0 ]]
	then
		debug "Ignore regular boot"
		return
	fi

	debug "Detected tryboot boot"

	if ! reboot="$(get_reboot_flag)"
	then
		error "reboot: Cannot get oneshot reboot flag"
		return 1
	fi

	# the oneshot reboot flag is already set, do nothing
	if [[ "$reboot" -eq 1 ]]
	then
		debug "Ignore oneshot reboot flag"
		return
	fi

	# the slot is the primary slot, do nothing
	if [[ "$slot" == "$primary" ]]
	then
		debug "Ignore primary slot"
		return
	fi

	# the slot is not yet the primary slot, update autoboot.txt
	set_primary_persistent
	debug "File updated"
}

# Output the bootname's slot of the boot_partition set in the section [all] in
# the file autoboot.txt if the oneshot reboot flag is unset, or the slot with
# boot_partition set in the section [tryboot] in the file autoboot.txt if the
# oneshot reboot flag is set.
#
# Note: The boot_partition device **MUST** be defined in system.conf; the slot
# for the boot partition is bootname'd, and the slot for the root is parent'ed
# to it.
#
# https://rauc.readthedocs.io/en/latest/integration.html#grouping-slots
#
# Important: the Raspberry Pi firmware tells the boot'ed partition number but
# it says no word about the boot'ed device (i.e. it says ~~/dev/mmcblk0p~~1).
get_primary() {
	local boot_partition
	local reboot
	local i

	source_file "${RASPBERRYPI_AUTOBOOT_TXT:-/boot/autoboot.txt}"
	boot_partition="$INI__ALL__BOOT_PARTITION"

	if ! reboot="$(get_reboot_flag)"
	then
		error "reboot: Cannot get oneshot reboot flag"
		return 1
	fi

	# the oneshot reboot flag is set, use [tryboot] section
	if [[ "$reboot" -eq 1 ]]
	then
		debug "Detected oneshot reboot flag"
		boot_partition="$INI__TRYBOOT__BOOT_PARTITION"
	fi

	source_file "${RAUC_SYSTEM_CONF:-/usr/lib/rauc/system.conf}"
	for i in "${INI[@]}"
	do
		local partition
		local bootname
		local v

		if ! [[ "$i" =~ ^slot\. ]]
		then
			continue
		fi

		v="$i"
		v="${v//./_}"
		v="${v//-/_}"
		eval "bootname=\$INI__${v^^}__BOOTNAME"
		if [[ "$bootname" != "$boot_partition" ]]
		then
			continue
		fi

		echo "$bootname"
		return
	done

	warning "${RAUC_SYSTEM_CONF:-/usr/lib/rauc/system.conf}: $boot_partition: No such bootname"
	return 1
}

# Set the other slot as primary temporarily toggling the oneshot reboot flag.
#
# Do nothing otherwise.
set_primary() {
	local primary
	local reboot

	if ! primary="$(get_primary)"
	then
		error "primary: Cannot get slot"
		return 1
	fi

	# the slot is already the primary slot, do nothing
	if [[ "$1" == "$primary" ]]
	then
		debug "Detected primary slot"
		return
	fi

	if ! reboot="$(get_reboot_flag)"
	then
		error "reboot: Cannot get oneshot reboot flag"
		return 1
	fi

	# the slot is already already the primary slot in autoboot.txt (the
	# onehost reboot flag is set), clear the oneshot reboot flag
	if [[ "$reboot" -eq 1 ]]
	then
		set_reboot_flag 0
		debug "Oneshot reboot flag cleared"
		return
	fi

	# The slot is not yet the primary slot in autoboot.txt (the oneshot
	# reboot flag is unset), set the oneshot reboot flag
	set_reboot_flag 1
	debug "Oneshot reboot flag set"
}

# Output the bootname's slot of the partition number set by the bootloader in
# the fdt using the RAUC system.conf file.
get_current() {
	local partition
	local slot

	if ! partition="$(fdtget /sys/firmware/fdt /chosen/bootloader partition)"
	then
		error "partition: Cannot get bootloader partition"
		return 1
	fi

	if ! slot="$(get_slot "$partition")"
	then
		error "$partition: Cannot get slot"
		return 1
	fi

	echo "$slot"
}

source_file "${RAUC_SYSTEM_CONF:-/usr/lib/rauc/system.conf}"
RASPBERRYPI_AUTOBOOT_TXT="${INI__SYSTEM__RASPBERRYPI_AUTOBOOT_TXT:-/boot/autoboot.txt}"

if [ "$1" = "get-state" ]
then
	shift
	get_state "$@"
elif [ "$1" = "set-state" ]
then
	shift
	set_state "$@"
elif [ "$1" = "get-primary" ]
then
	shift
	get_primary "$@"
elif [ "$1" = "set-primary" ]
then
	shift
	set_primary "$@"
elif [ "$1" = "get-current" ]
then
	shift
	get_current "$@"
fi
